# Generated by Django 4.1.7 on 2023-05-10 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_invoice_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='price',
            new_name='totalAmount',
        ),
    ]
